@startuml

!include skin-state.iuml
hide empty description

[*] --> setup
state setup {
    setup: create list of joints
    setup: create sequence of joins
    setup: set calibration routine per joint

}
setup --> idle
idle --> activate_joint :user starts mastering
idle: set first joint as target for mastering
idle: show dialog
idle: wait
activate_joint --> move_to_pose
activate_joint: prepare stuff
activate_joint: start move
move_to_pose --> calibrate_joint :pose reached
move_to_pose: wait until pose is reached
calibrate_joint --> joint_calibrated :done
calibrate_joint: set recording
calibrate_joint: run calibration routine
calibrate_joint: reset recording
joint_calibrated --> move_to_pose :user not satisfied,\ndo again
joint_calibrated --> save_offsets :user satisfied
save_offsets --> activate_joint :next joint exists
save_offsets: get next joint and set
save_offsets: set joint as target for mastering
save_offsets --> move_to_zero :**NO** next joint
move_to_zero: start moving to zero pose
move_to_zero: wait until position is reached
move_to_zero --> finished: position reached
finished: show dialog
finished --> [*]
--
error1: try to solve
error1: try to return to a valid state
error1 --> [*]: solving and returning\nis not possible
--
abort_by_user --> [*] :user abort, stop program
abort_by_user: clean up pins
abort_by_user: clean up signals

@enduml